// TRIP COUNT
export const GET_TRIPS_COUNT_START = 'GET_TRIPS_COUNT_START'
export const GET_TRIPS_COUNT_SUCCESS = 'GET_TRIPS_COUNT_SUCCESS'
export const GET_TRIPS_COUNT_FAIL = 'GET_TRIPS_COUNT_FAIL'

/*  ********************************************************  */

/* ************************************************************/
// Get all trip data

export const GET_ALL_TRIP_DATA_START = 'GET_ALL_TRIP_DATA_START'
export const GET_ALL_TRIP_DATA_SUCCESS = 'GET_ALL_TRIP_DATA_SUCCESS'
export const GET_ALL_TRIP_DATA_FAIL = 'GET_ALL_TRIP_DATA_FAIL'

/*******************************************/
// Trip

export const SET_TRIP_OBJECT = 'SET_TRIP_OBJECT'

// Edit itinerary
export const SET_ITINERARY_TRIP_OBJECT = 'SET_ITINERARY_TRIP_OBJECT'
export const GET_ITINERARY_DATA_START = 'GET_ITINERARY_DATA_START'
export const GET_ITINERARY_DATA_SUCCESS = 'GET_ITINERARY_DATA_SUCCESS'
export const GET_ITINERARY_DATA_FAIL = 'GET_ITINERARY_DATA_FAIL'
export const CHANGE_ITINERARY_SELECT_OPTION = 'CHANGE_ITINERARY_SELECT_OPTION'
export const EDIT_ITINERARY_DATA = 'EDIT_ITINERARY_DATA'

// Todo
export const SET_TRIP_TODO_OBJECT = 'SET_TRIP_TODO_OBJECT'
export const CREATE_TODO_ITEM_SUCCESS = 'CREATE_TODO_ITEM_SUCCESS'
export const CREATE_TODO_ITEM_FAIL = 'CREATE_TODO_ITEM_FAIL'
export const GET_TODO_DATA_START = 'GET_TODO_DATA_START'
export const GET_TODO_DATA_SUCCESS = 'GET_TODO_DATA_SUCCESS'
export const GET_TODO_DATA_FAIL = 'GET_TODO_DATA_FAIl'
export const SHOW_SLIDER = 'SHOW_SLIDER'
export const HIDE_SLIDER = 'HIDE_SLIDER'
export const DRAG_AND_DROP = 'DRAG_AND_DROP'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const SHOW_EDIT_WINDOW = 'SHOW_EDIT_WINDOW'
export const HIDE_EDIT_WINDOW = 'HIDE_EDIT_WINDOW'
export const EDIT_TODO_ITEM_START = 'EDIT_TODO_ITEM_START'
export const EDIT_TODO_ITEM_FAIL = 'EDIT_TODO_ITEM_FAIL'
export const EDIT_TODO_ITEM_SUCCESS = 'EDIT_TODO_ITEM_SUCCESS'
export const DELETE_TODO_ITEM_START = 'DELETE_TODO_ITEM_START'
export const DELETE_TODO_ITEM_FAIL = 'DELETE_TODO_ITEM_FAIL'
export const DELETE_TODO_ITEM_SUCCESS = 'DELETE_TODO_ITEM_SUCCESS'
